### PR TITLE
Unit tests for all the functions added

### PR DESCRIPTION
**Pull request by ABHISHEKMAHALUNGE**

### CODE REVIEW

**Comment by ABHISHEKMAHALUNGE** [comment]
@adityabisoi can it be merged?

**Comment by adityabisoi** [comment]
@ABHISHEKMAHALUNGE I see empty lines in core/infixToPostfix.test.js. Also, please include steps to test the functions in README.

**Comment by adityabisoi** [comment]
@ABHISHEKMAHALUNGE Any leads?

**Comment by ABHISHEKMAHALUNGE** [comment]
Yes on it.

**Comment by adityabisoi** [comment]
Proper documentation for steps to run the test is still not included in the README.

**Pull request closed without merging**
