### PR TITLE
Design form UI

### PR DESCRIPTION
**Pull request by luckykumarirai**
Screenshot from 2020-12-15 10-22-21
I have designed this form using Material UI.

### CODE REVIEW

**Comment by adityabisoi** [comment]
The design can be improved. Nice work with the implementation, though. Please apply your creativity a little more.

**Comment by luckykumarirai** [comment]
Thanks , Sure I will do that.

**Comment by adityabisoi** [comment]
@luckykumarirai Are you on this?

**Comment by luckykumarirai** [comment]
Yes,
I am working but can u explain what kind of design u want for better UI.i have added Navbar on this page.plz explain  
Screenshot from 2020-12-18 18-06-55

**Comment by adityabisoi** [comment]
The `postfix operation` should be invisible, and should appear only when conversion results are shown. Also, what does the leftmost button do?

**Comment by luckykumarirai** [comment]
okay, I will add all those features which u mentation.

**Comment by luckykumarirai** [comment]
Now postfix operation only visible after a click on submit and the design also improved.
##Before submit-
Screenshot from 2020-12-19 16-48-20
##After submit-
Screenshot from 2020-12-19 17-11-39

**Comment by adityabisoi** [comment]
Nice work with the UI. However, I do not see the conversion pages for other routes. Can you do that, if not, I would have to create new issue.

**Comment by luckykumarirai** [comment]
Please accept this PR  and you should create new issues sure I can work on that issue also.

**Pull request merged**
