### PR TITLE
Added issue template for the feature request

### LINKED ISSUE #3: Add issue template: feature request
Add an issue template for requesting new features in the project.

### PR DESCRIPTION
**Pull request by iamrajiv**
Fixes: #3

### CODE REVIEW

**Comment by iamrajiv** [comment]
@adityabisoi please review

**Comment by adityabisoi** [comment]
@iamrajiv Please add a better template.

**Comment by iamrajiv** [comment]
@adityabisoi Can you give some requirements needed for a template?

**Comment by adityabisoi** [comment]
See [this](https://github.com/go-fed/activity/blob/master/.github/ISSUE_TEMPLATE/feature-request-template.md)

**Pull request merged**
