### PR TITLE
React Invalid Hooks Issue Fix

### PR DESCRIPTION
**Pull request by manav-06**
After installation and running the app, it shows this issue:
image
- Material UI v4 and useStyle hook used in components/navbar was causing this error. 
- Changed Material UI version to 5 and used css() property in 'emotion/react' instead of useStyle hook.

### CODE REVIEW

**Comment by adityabisoi** [comment]
Changes look good, please remove yarn.lock from your commit.

**Comment by manav-06** [comment]
It is removed already

**Comment by manav-06** [comment]
It has been removed already

**Comment by manav-06** [comment]
@adityabisoi @subhangi2731 Do let me know if  there are any modifications needed in this PR.

**Comment by adityabisoi** [comment]
@manav-06 The header on the homepage seems to be off.
Screenshot from 2021-12-09 17-59-52

**Comment by manav-06** [comment]
image
@adityabisoi homepage fixed!

**Comment by adityabisoi** [comment]
Great work!

**Pull request merged**
